version: '3'
services:
  rabbitmq:
    image: "rabbitmq:alpine"
    restart: always
  producer:
    build: ./producer
    environment:
      - RabbitURL=amqp://guest:guest@rabbitmq:5672
    links:
      - rabbitmq
  consumer:
    build: ./consumer
    environment:
      - RabbitURL=amqp://guest:guest@rabbitmq:5672
    links:
      - rabbitmq


